### ISSUE TITLE
woke compile crashes when using `import * as libraryName from "path/to/lib"

### ISSUE THREAD

**Issue by DrakeEvans** [Ackee-Blockchain/wake#233]
language server as well as `woke compile` crash when using import * as foobar from "path/to/foobar":
Changing to import { foo, bar } from "path/to/foobar" resolves the issue

**Comment by michprev** [comment]
Hello @DrakeEvans,
can you provide a concrete example or at least a crash message? Thank you.

**Comment by DrakeEvans** [comment]
You can reproduce here: https://github.com/DrakeEvans/woke-bug

From Language Server in vscode:

[Trace - 9:43:10 AM] Received notification 'window/logMessage'.
Params: {
    "type": 1,
    "message": "Traceback (most recent call last):\n  File \"/opt/homebrew/lib/python3.10/site-packages/woke/lsp/server.py\", line 264, in _task_done_callback\n    task.result()\n  File \"/opt/homebrew/lib/python3.10/site-packages/woke/lsp/lsp_compiler.py\", line 181, in run\n    await self.__compilation_loop()\n  File \"/opt/homebrew/lib/python3.10/site-packages/woke/lsp/lsp_compiler.py\", line 879, in __compilation_loop\n    await self.__compile(self.__discovered_files)\n  File \"/opt/homebrew/lib/python3.10/site-packages/woke/lsp/lsp_compiler.py\", line 796, in __compile\n    self.__ir_reference_resolver.run_post_process_callbacks(\n  File \"/opt/homebrew/lib/python3.10/site-packages/woke/ast/ir/reference_resolver.py\", line 103, in run_post_process_callbacks\n    callback(callback_params)\n  File \"/opt/homebrew/lib/python3.10/site-packages/woke/ast/ir/meta/identifier_path.py\", line 70, in _post_process\n    assert isinstance(referenced_declaration, DeclarationAbc)\nAssertionError\n"
}


[Error - 9:43:10 AM] Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/woke/lsp/server.py", line 264, in _task_done_callback
    task.result()
  File "/opt/homebrew/lib/python3.10/site-packages/woke/lsp/lsp_compiler.py", line 181, in run
    await self.__compilation_loop()
  File "/opt/homebrew/lib/python3.10/site-packages/woke/lsp/lsp_compiler.py", line 879, in __compilation_loop
    await self.__compile(self.__discovered_files)
  File "/opt/homebrew/lib/python3.10/site-packages/woke/lsp/lsp_compiler.py", line 796, in __compile
    self.__ir_reference_resolver.run_post_process_callbacks(
  File "/opt/homebrew/lib/python3.10/site-packages/woke/ast/ir/reference_resolver.py", line 103, in run_post_process_callbacks
    callback(callback_params)
  File "/opt/homebrew/lib/python3.10/site-packages/woke/ast/ir/meta/identifier_path.py", line 70, in _post_process
    assert isinstance(referenced_declaration, DeclarationAbc)
AssertionError

[Error - 9:43:10 AM] The Tools for Solidity server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.

**Comment by DrakeEvans** [comment]
https://github.com/DrakeEvans/woke-bug/blob/b90a5e67b91695b8abf013c863a0eb7c46858dbd/test/Counter.t.sol#L6

This is the line which causes the problem

**Comment by michprev** [comment]
Thank you for the provided example. I was able to reproduce the bug and it should be fixed in the next version.

**Comment by michprev** [comment]
All kinds of import directives should be handled nicely now. Feel free to reopen if the issue re-appears.
