### ISSUE TITLE
woke does not detect pipx

### ISSUE THREAD

**Issue by mtugan** [Ackee-Blockchain/wake#272]
It would possibly be preferable if the woke would be able to detect pipx and use it instead of pip or offer an option in VSC console output if pip is not detected for this.

Note that installing woke via pipx manually works and it detects the executable after this.

**Comment by michprev** [comment]
I agree this is a good idea. Since this change can cause some issues (especially if a user already has globally installed woke using pip), I will postpone this change for the next major release and try to cover all possible edge cases that would cause the automatic installation to fail.

**Comment by michprev** [comment]
pipx installation is now used by default (if possible) in Tools for Solidity 1.11.0 :tada:
