### ISSUE TITLE
💡 [REQUEST] - VSCode Support For Foundry Test & Script File

### ISSUE THREAD

**Issue by CSWellesSun** [Ackee-Blockchain/wake#355]
### Summary

In a Foundry project, test and script files like `a.t.sol` or `a.s.sol` lack support in VSCode for features like navigation or reference lookup.

### Basic Example

Add navigation or reference lookup just as `.sol` files in foundry projects

### Drawbacks

No drawbacks. Everyone using foundry will be grateful !

**Comment by michprev** [comment]
Hello @CSWellesSun,
analysis for Foundry `test` and `script` files can be enabled by removing `test` and `script` directories from the compiler `exclude_paths` setting, either in VS Code settings or TOML config file (depending what you currently use).

**Comment by CSWellesSun** [comment]
cool really thx!
